server:
  port: 8080

# 可访问全部敏感端口
# /evn 服务的全部环境变量信息
# /health 当前服务状态
endpoints:
  sensitive: false

eureka:
  instance:
    hostname: localhost
    #心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: in
  server:
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
management:
  security:
    enabled: false      

#logging:
#  level:
#    com.netflix: DEBUG
      