server:
  port: 9527
spring:
  application:
    name: langya-conf
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared/langya-services
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lucasXiang/langya
          search-paths: langya-services,langya-gateway
          default-label: master
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    # 抓取服务列表
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    # 心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    # 告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    

