server:
  port: 9527
spring:
  application:
    name: langya-conf
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared/langya-services
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lucasXiang/langya
          search-paths:
            - langya-services
          default-label: master
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    

