# for test in applicationStarting
foo: hello-world (foo version 1) 

server:
  port: 8762
# rabbitmq 配置信息
spring:
  #rabbitmq配置
  rabbitmq:
    host: 192.168.61.129
    port : 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
